/* AURALINK dashboard client.
 *
 * Connects to the local Python bridge (auralink/server.py) over a WebSocket:
 *   - receives live state { bpm, zone, style_label, prompt, playing, bio_mode }
 *     and renders it into the dashboard, and
 *   - sends control messages (play/stop, bio toggle, manual tempo) back.
 *
 * Audio is generated by Magenta and plays on the host machine, not here — this
 * page is a telemetry + control surface only.
 */

// ── Per-zone display flavour (cosmetic; driven by the live HR zone) ──────────
const ZONES = {
  calm:   { name: "Stillwater",       meta: "Generative · ambient drift", mode: "RESTING",   key: "Am",  chord: "Am9",  scale: "Aeolian",  groove: "1/1" },
  rest:   { name: "Morning Threshold",meta: "Generative · warm pads",     mode: "EASY",      key: "Cm",  chord: "Cm7",  scale: "Dorian",   groove: "1/2" },
  active: { name: "Open Current",     meta: "Generative · moving bass",   mode: "SYNCOPATION",key: "Em", chord: "Em7",  scale: "Dorian",   groove: "1/4" },
  peak:   { name: "Crest",            meta: "Generative · driving pulse", mode: "DRIVING",   key: "Gm",  chord: "Gm7",  scale: "Phrygian", groove: "1/8" },
};

const $ = (id) => document.getElementById(id);
let ws = null;
let state = { bpm: 0, zone: "", playing: false, bio_mode: true, manual_bpm: 60 };

// ── WebSocket ────────────────────────────────────────────────────────────────
function connect() {
  ws = new WebSocket(`ws://${location.host}/ws`);
  ws.onmessage = (ev) => {
    try { applyState(JSON.parse(ev.data)); } catch (_) {}
  };
  ws.onclose = () => setTimeout(connect, 1000); // auto-reconnect
}

function send(msg) {
  if (ws && ws.readyState === WebSocket.OPEN) ws.send(JSON.stringify(msg));
}

function resolveSourceLabel(s) {
  const explicit = (s.heartbeat_source || "").trim();
  if (explicit) return explicit;
  // Backward-compatible inference for older server payloads.
  if (s.manual_override_allowed === false) return "Pulsoid";
  if (s.manual_override_allowed === true) return "Simulated";
  return "Unknown";
}

// ── Render live state into the DOM ───────────────────────────────────────────
function applyState(s) {
  state = s;
  const heartBpm = Math.round((s.heart_bpm ?? s.bpm) || 0);
  const tempoBpm = Math.round((s.effective_bpm ?? s.bpm) || 0);
  const z = ZONES[s.zone] || ZONES.rest;
  const sourceLabel = resolveSourceLabel(s);
  const source = sourceLabel.toLowerCase();

  setText("bpmNum", heartBpm);
  setText("epSource", sourceLabel);
  setText("lpSource", sourceLabel);
  setText("lpHeart", `${heartBpm} BPM`);
  setText("lpZone", s.zone || "rest");
  setText("heartbeatSource", `HEARTBEAT SOURCE: ${sourceLabel.toUpperCase()}`);
  const sourceBadge = $("heartbeatBadge");
  if (sourceBadge) {
    sourceBadge.classList.remove("source-pulsoid", "source-simulated", "source-unknown");
    if (source === "pulsoid") sourceBadge.classList.add("source-pulsoid");
    else if (source === "simulated") sourceBadge.classList.add("source-simulated");
    else sourceBadge.classList.add("source-unknown");
  }

  setText("cpKey", z.key);
  setText("cpChord", z.chord);
  setText("cpScale", z.scale);

  // Play/pause button.
  const icon = $("playIcon");
  if (icon) {
    icon.innerHTML = s.playing
      ? '<rect x="6" y="4.5" width="3" height="11" rx="1" fill="white"/><rect x="11" y="4.5" width="3" height="11" rx="1" fill="white"/>'
      : '<path d="M7 4.5l10 5.5-10 5.5V4.5z" fill="white"/>';
  }

}

function setText(id, v) {
  const el = $(id);
  if (el) el.textContent = v;
}

// ── Control handlers (referenced by inline onclick= in index.html) ───────────
function togglePlay() { send({ action: state.playing ? "stop" : "play" }); }
function setParam(name, value) {
  const map = { reverb: "epReverb", density: "epDensity", bio: "epBio" };
  setText(map[name], value);
}

window.togglePlay = togglePlay;
window.setParam = setParam;

// ── Heartbeat ECG canvas (animation speed follows live BPM) ──────────────────
function startHeartbeatCanvas() {
  const canvas = $("hbCanvas");
  if (!canvas) return;
  const ctx = canvas.getContext("2d");
  let x = 0;
  const pts = [];

  function resize() {
    canvas.width = canvas.clientWidth * devicePixelRatio;
    canvas.height = canvas.clientHeight * devicePixelRatio;
  }
  resize();
  addEventListener("resize", resize);

  function beatY(phase) {
    // A simple ECG-like spike at the start of each beat cycle.
    if (phase < 0.10) return 0;
    if (phase < 0.14) return -0.25;
    if (phase < 0.18) return 1.0;   // R spike
    if (phase < 0.22) return -0.5;
    if (phase < 0.30) return 0.1;
    return 0;
  }

  let last = performance.now();
  let cycle = 0;
  function frame(now) {
    const dt = (now - last) / 1000;
    last = now;
    const bpm = Math.max(30, state.bpm || 60);
    cycle += dt * (bpm / 60); // beats elapsed
    const phase = cycle % 1;

    const w = canvas.width, h = canvas.height, mid = h / 2;
    pts.push(mid - beatY(phase) * h * 0.34);
    const maxPts = Math.floor(w / (2 * devicePixelRatio));
    while (pts.length > maxPts) pts.shift();

    ctx.clearRect(0, 0, w, h);
    ctx.lineWidth = 2 * devicePixelRatio;
    ctx.strokeStyle = "#e8604a";
    ctx.shadowColor = "rgba(232,96,74,0.6)";
    ctx.shadowBlur = 8 * devicePixelRatio;
    ctx.beginPath();
    const step = w / Math.max(1, maxPts - 1);
    pts.forEach((y, i) => (i ? ctx.lineTo(i * step, y) : ctx.moveTo(0, y)));
    ctx.stroke();
    requestAnimationFrame(frame);
  }
  requestAnimationFrame(frame);
}

// ── Boot ─────────────────────────────────────────────────────────────────────
connect();
startHeartbeatCanvas();
