#!/usr/bin/env python3
"""AURALINK — a heartbeat plays Magenta RealTime 2 as a live instrument.

On-challenge demo for the Google DeepMind / Magenta RealTime 2 track:

    body (heartbeat)  ->  signal (BPM)  ->  Magenta RealTime 2  ->  sound

Magenta RT2 generates ALL of the audio, live and continuously — including the
four-on-the-floor TR-808 kick. There are no samples: the kick, bass, and texture
are all generated by the model. The heart rate steers Magenta in real time by
selecting the live style/prompt for its heart-rate zone (calm pads -> steady
808 groove -> driving techno -> peak-time rave) and by nudging the tempo word in
the prompt, all re-embedded on the fly via MagentaEngine.set_style().

Run live:
    python auralink.py                  # simulated heartbeat ~60 BPM
    python auralink.py --bpm 80 --steady

Offline (no audio device; writes a WAV to verify the pipeline):
    python auralink.py --render 12 --bpm 90

Quick model check:
    python auralink.py --selftest
"""

from __future__ import annotations

import argparse
import time

import numpy as np

from heartbeat import HeartbeatSource, PulsoidHeartbeat, SimulatedHeartbeat
from magenta_engine import SAMPLE_RATE, MagentaEngine

# Heart-rate zones -> live Magenta style. The prompt is the entire instrument;
# Magenta generates the kick and everything else. A `{bpm}` token is filled with
# the current heart rate so tempo tracks the body.
HR_ZONES = [
    (0, 58, "calm",
     "calm ambient soundscape, warm evolving pads, slow deep drone, "
     "soft four on the floor TR-808 kick, meditative, {bpm} BPM"),
    (58, 72, "rest",
     "downtempo organic groove, deep TR-808 sub kick four on the floor, "
     "warm bassline, gentle steady pulse, hypnotic, {bpm} BPM"),
    (72, 88, "active",
     "driving four on the floor techno, punchy TR-808 kick drum, "
     "rolling bassline, hypnotic, {bpm} BPM"),
    (88, 999, "peak",
     "energetic peak-time techno, hard pumping TR-808 kick four on the floor, "
     "fast arpeggios, euphoric rave, {bpm} BPM"),
]


def hr_to_style(bpm: float) -> tuple[str, str]:
    """Map a heart rate to a (zone_label, magenta_prompt) with tempo filled in."""
    for low, high, label, prompt in HR_ZONES:
        if low <= bpm < high:
            return label, prompt.format(bpm=int(round(bpm)))
    label, prompt = HR_ZONES[-1][2], HR_ZONES[-1][3]
    return label, prompt.format(bpm=int(round(bpm)))


class Auralink:
    """Wires a heartbeat to Magenta RealTime 2 — Magenta is the only sound source."""

    def __init__(
        self,
        engine: MagentaEngine,
        heart: HeartbeatSource,
        restyle_bpm_delta: float = 4.0,
    ) -> None:
        self.engine = engine
        self.heart = heart
        self.restyle_bpm_delta = restyle_bpm_delta
        self._current_zone = ""
        self._last_bpm = -1.0

    # -- Live mapping: heart rate -> Magenta style ------------------------

    def update_style_for_hr(self) -> None:
        """Retune Magenta's live style when the zone changes or tempo drifts."""
        bpm = self.heart.bpm
        zone, prompt = hr_to_style(bpm)
        if zone != self._current_zone or abs(bpm - self._last_bpm) >= self.restyle_bpm_delta:
            self._current_zone = zone
            self._last_bpm = bpm
            self.engine.set_style(prompt, label=f"{zone} @ {bpm:.0f} BPM")

    # -- Audio block (pure Magenta) ---------------------------------------

    def mix_block(self, frames: int, *, offline: bool = False) -> np.ndarray:
        """Return one (frames, 2) block straight from Magenta."""
        out = self.engine.read(frames, offline=offline)
        np.clip(out, -1.0, 1.0, out=out)
        return out.astype(np.float32)

    # -- Outputs ----------------------------------------------------------

    def run(self) -> None:
        """Play AURALINK live until interrupted (Ctrl-C)."""
        import sounddevice as sd

        self.update_style_for_hr()
        self.engine.start()
        self.heart.start()

        def callback(outdata, frames, _time, status):
            if status:
                print(f"Playback status: {status}")
            outdata[:] = self.mix_block(frames)

        print("AURALINK live: heartbeat -> Magenta RealTime 2 (all audio). Ctrl-C to stop.")
        try:
            with sd.OutputStream(
                samplerate=SAMPLE_RATE,
                channels=2,
                dtype="float32",
                callback=callback,
            ):
                while not self.engine.stopped:
                    self.update_style_for_hr()  # poll HR -> restyle Magenta live
                    time.sleep(0.25)
        except KeyboardInterrupt:
            print("\nStopping...")
        finally:
            self.heart.stop()
            self.engine.stop()

    def render(self, seconds: float, path: str = "auralink_demo.wav") -> str:
        """Render `seconds` of the Magenta pipeline to a WAV (offline, no device)."""
        import soundfile as sf

        self.update_style_for_hr()
        total = int(seconds * SAMPLE_RATE)
        block = 4800  # 0.1s
        chunks = []
        rendered = 0
        while rendered < total:
            self.update_style_for_hr()
            n = min(block, total - rendered)
            chunks.append(self.mix_block(n, offline=True))
            rendered += n
        audio = np.concatenate(chunks, axis=0)
        sf.write(path, audio, SAMPLE_RATE)
        print(f"Wrote {path} ({seconds:g}s).")
        return path


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bpm", type=float, default=60.0, help="Base heart rate (BPM).")
    parser.add_argument(
        "--steady", action="store_true", help="Pin a fixed heart rate (no drift)."
    )
    parser.add_argument("--size", default="mrt2_small", help="Magenta model variant.")
    parser.add_argument(
        "--temperature",
        type=float,
        default=1.0,
        help="Magenta sampling temperature. Lower = steadier kick (default 1.0).",
    )
    parser.add_argument(
        "--render",
        type=float,
        default=None,
        metavar="SECONDS",
        help="Render to a WAV instead of playing live (no audio device needed).",
    )
    parser.add_argument(
        "--selftest",
        action="store_true",
        help="Generate a few Magenta chunks, report real-time factor, then exit.",
    )
    parser.add_argument(
        "--pulsoid",
        action="store_true",
        help="Use a live Pulsoid heart rate (e.g. Apple Watch) instead of the "
        "simulated heartbeat.",
    )
    parser.add_argument(
        "--pulsoid-token",
        default=None,
        help="Pulsoid access token. Defaults to the PULSOID_TOKEN env var. "
        "Keep it secret; never commit it.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    engine = MagentaEngine(size=args.size, temperature=args.temperature)
    engine.load_model()

    if args.selftest:
        engine.set_style(hr_to_style(args.bpm)[1])
        engine.selftest()
        return 0

    if args.pulsoid:
        heart: HeartbeatSource = PulsoidHeartbeat(token=args.pulsoid_token)
    else:
        heart = SimulatedHeartbeat(bpm=args.bpm, drift=0.0 if args.steady else 8.0)
    app = Auralink(engine=engine, heart=heart)

    if args.render is not None:
        app.render(args.render)
    else:
        app.run()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
